version: "3.3"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: Kursach20
      POSTGRES_DB: library
      POSTGRES_HOST: 127.0.0.1
    volumes:
      - ./db/data1:/var/lib/postgresql/data
  web:
    image: electpo/library_web:latest
    environment:
      DB_HOST: 'db'
      DB_PORT: 5432
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8005:8000"
    volumes:
      - .:/libraryapp
    depends_on:
      - db