# Generated by Django 3.1.7 on 2021-03-13 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_security', models.UUIDField(default=uuid.uuid4)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('e', 'Expectation'), ('n_a', 'Not available')], default='n_a', max_length=3)),
                ('authors', models.ManyToManyField(to='libraryapp.Author')),
                ('genre', models.ManyToManyField(to='libraryapp.Genre')),
                ('id_inst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookinstance')),
            ],
        ),
    ]
