# Generated by Django 3.1.7 on 2021-04-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20210410_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_inst',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookinstance'),
        ),
    ]
